### ISSUE TITLE
HTML tag in "Mergeability" message

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/miq_bot#242]
When the bot posts a message about it is unable to merge, it has started to add a HTML tag "<pr_mergeability_checker />This pull request is not mergeable. Please rebase and repush."  Can this be fixed to remove the tag?
<img width="819" alt="screen shot 2017-01-06 at 11 08 56 am" src="https://cloud.githubusercontent.com/assets/2414647/21726045/a140ff0c-d400-11e6-9419-460992b99f2c.png">

**Comment by chriskacerguis** [comment]
@miq-bot add_label bug

**Comment by Fryguy** [comment]
Fixed in https://github.com/ManageIQ/miq_bot/commit/76d154ea5fc0051f62aa5ba34a889cf58ea700da which was deployed yesterday.  Moving forward you won't see them in new comments.  This change doesn't go back and remove the old comments, however if you see one you can just delete it.  If it's really necessary, I can whip up a script to find and fix or delete the old ones, but I didn't think it was worth the effort at the moment.
