### ISSUE TITLE
Required info reminder

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/miq_bot#250]
Would be nice if we can define the necessary info for a ticket (per repo) and that the system will prompt (similar to the unmergable message) for that info.  For example, you can make a pivotal tracker link required, and for it to require one or more labels.

**Comment by Fryguy** [comment]
Oh this is a really interesting idea

**Comment by Fryguy** [comment]
Some time ago I had opened a number of issues on specific things we want to be reminded of.  Most of them had been labeled `requires_batch_commenting` because we had considered using batch commenting at the time (and since now batch commenting is implemented, we can do these).  See https://github.com/ManageIQ/miq_bot/issues?q=is%3Aissue+is%3Aopen+label%3A%22needs+batch+commenting%22

@chriskacerguis Can you please open a separate issue per thing you want to be reminded of that aren't already in that list, so that we can knock them down one by one?

**Comment by Fryguy** [comment]
Or if there are any already open issue you'd like priority on, bump them with a :+1: comment
