### ISSUE TITLE
Print the current rubocop.yml location and sha1

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/miq_bot#28]
For newcomers, we should link to the current yml and the how to setup rubocop locally doc.

For oldies, it would be useful to easily grab the new yml if there are cop messages online but not locally (user has an old yml)

For maintainers, it would be useful to link directly to the yml the bot is using,at a commit, to verify they updated the bot to the latest code.

Summary:
- Current yml so users can shift click and download
- Link to current bot commit or tag (run using bot at commit xyz)
- link to setting up rubocop locally

**Comment by Fryguy** [comment]
This is changing so that we will require the .rubocop.yml in every repo, so I am going to close this.  At a minimum they can inherit from the manageiq guides if that is what is wanted.  Here is an example PR that does just that: https://github.com/ansible/ansible_tower_client_ruby/pull/51

cc @bdunne
