### ISSUE TITLE
SideTiq is no longer maintained

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#282]
According the SideTiq README, SideTiq is no longer going to be maintained because it would have to be rewritten to deal with the Sidekiq 5 update.  We may want to consider alternatives (though they may also run into the same rewrite problem).  Some that I've found:

- https://github.com/moove-it/sidekiq-scheduler
- https://github.com/ondrejbartas/sidekiq-cron (So far I prefer this one)

**Comment by chrisarcand** [comment]
This isn't as trivial as one might think, after spiking it.

Both these gems lack a major feature that Sidetiq has: Redis-based locking to synchronize multiple Sidekiq processes. You don't need to care about multiple scheduled jobs being added because Sidetiq Just Works™ across multiple processes, which we do.

So, in the future when/if we want to do this, keep in mind that we will need to build our own scheduler. A Sidekiq worker whose job is just to schedule the others correctly.

**Comment by Fryguy** [comment]
@chrisarcand Would it be possible to add the redis-based locking to sidekiq-cron as a feature?

**Comment by Fryguy** [comment]
https://github.com/mattyr/sidecloq has the locking we were missing before, so it's pretty trivial to switch now.

**Comment by chrisarcand** [comment]
Huzzah!
