### ISSUE TITLE
[RFE] PRs should support add_reviewer action

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/miq_bot#337]
See https://github.com/ManageIQ/manageiq/pull/14552#issuecomment-289928737 for example usage.

**Comment by moolitayer** [comment]
cc @abonas

**Comment by abonas** [comment]
I also wondered about this ability [recently](https://github.com/ManageIQ/manageiq/pull/14543#issuecomment-290023927)

**Comment by NickLaMuro** [comment]
From @chriskacerguis [comment](https://github.com/ManageIQ/miq_bot/issues/354#issuecomment-317778391) in the duplicate issue:

> Question...should there be some kind of inverse for this?
> 
> @miq-bot remove_review @username
> @miq-bot un_review @username ???

I think this is something that really doesn't exist even with the `assign` functionality, and has a bit of a permission issue involved with it.  I would say that if we were to do this, you could only remove yourself, and otherwise this is something that the project owners already have access to do.

**Comment by Fryguy** [comment]
There is a feature for dismissing reviews that only those with merge rights can do, but it requires a reason.  So it we wanted to expose that, the command would have to be something like

`@miq-bot remove_reviewer @Fryguy This is my reason for removing`

**Comment by chrisarcand** [comment]
I don't think there really needs to be an inverse at all. Designating a reviewer is *requesting* a review from someone; how common do you think it is for people to 'unrequest' someone to review something? It usually involves just requesting someone else anyway, if that person is gone.

I'd just do `@miqbot r? @username` (and/or `request_review`), which adds users to the reviewers list, and not go through the trouble of permissions for removing them as the exceptions are few and maintainers (write access) can handle that 2% case.

**Comment by NickLaMuro** [comment]
> I don't think there really needs to be an inverse at all.

@chrisarcand I would argue there is a use case, especially for those who are asked to review, but then feel like they don't have the proper skill set to review.  As an example:

https://github.com/ManageIQ/manageiq/pull/14525#issuecomment-299287404

In this case, Greg had permissions to remove himself, but for folks like myself, if I were assigned as a reviewer (right now, by someone who has merge rights), I have no way of removing myself.  This would give those without merge rights the ability to opt out of a review they were asked to do that they don't feel like they were qualified to do in the first place.

> It usually involves just requesting someone else anyway, if that person is gone.

Sure, this is fine I guess, but I would say there have been many times where I have had 4 or so reviewers stacked up on a single PR, and it would be in deadlock trying to determine who had the final say since maybe only 1 had given approval, and the rest are either in limbo or not responding.

**Comment by chrisarcand** [comment]
¯\\_(ツ)_/¯ Fair. Then for that use case, the command could be further simplified by not having a generic `remove_reviewer @username` to remove anyone, and having `decline_review` or whatever instead which only removes the person that gave the command. Maintainers, who have write access are the only ones who should be removing people that aren't themselves anyway(?)

**Comment by NickLaMuro** [comment]
Agreed, I think the `decline_review` suggestion makes more sense in this case, and agree that the "inverse command" probably should be just for the person who wants to remove themselves from the review process, and not require you to designate who you are trying to remove.

**Comment by chessbyte** [comment]
See https://developer.github.com/v3/pulls/review_requests/ for GitHub API

**Comment by Fryguy** [comment]
Closed via #408 and #419
