### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by PanSpagetka** [ManageIQ/miq_bot#351]
Since we are using ruby version 2.3.3 for Travis, shouldn't @miq-bot use same version? So I can use features like lonely operator without @miq-bot being angry at me :(

**Comment by Fryguy** [comment]
The reason the bot is 2.2 while the app is 2.3 is because we support Ruby 2.2+ for ManageIQ at the moment (and thus *can't* support `&.` at the moment).  However, it's too expensive to run both Ruby 2.2 and 2.3 travis builds on all of our PRs.  So, the decision was that since we ship our appliances with Ruby 2.3, we run tests with 2.3, and leave rubocop running with 2.2 to catch any syntax errors (`&.` would appear as a syntax error, since that's not in 2.2).

Once we officially support Ruby 2.4 and it's part of the appliance builds, we will bump the minimum to Ruby 2.3 and make the bot use 2.3.  See https://github.com/ManageIQ/manageiq/issues/14446 for progress.
