### ISSUE TITLE
Switch to HoundCI for linting

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#368]
HoundCI apparently now supports single-message for all issues, which is a big change that we've been waiting for.  I'd like to investigate dropping our bot linting entirely and moving to hound.

**Comment by ohadlevy** [comment]
I would love to see that experiment start - anything I could help to move this forward?

**Comment by ohadlevy** [comment]
setting up hound is pretty simple, see https://github.com/ohadlevy/miq_experimental_ui_plugin/blob/master/.hound.yml as an example.

in order to setup it up, you simply need to enable it on https://houndci.com/repos

**Comment by himdel** [comment]
@ohadlevy Can you add a sample of how this would actually look? So far I've only seen the per-line comments..

**Comment by ohadlevy** [comment]
you could see an example of hound output at https://github.com/ohadlevy/manageiq-ui-classic/pull/5

in terms of mails, this is the mail i got from github:
```
@houndci-bot commented on this pull request.

In app/assets/stylesheets/alerts.scss:

> @@ -219,8 +218,7 @@
       padding-right: 5px;
       text-decoration: none;
       transition: 250ms;
-
-      &::before {
+      &:before {
Expected empty line before rule rule-empty-line-before
Expected double colon pseudo-element notation selector-pseudo-element-colon-notation

In app/assets/stylesheets/about_modal_background.scss:

> @@ -3,11 +3,10 @@
 /* 'About' modal background image */
 
 .about-modal-pf {
-  background-color: $modal-about-pf-bg-color;
+  background-color: $modal-about-pf-bg-color
Missed semicolon CssSyntaxError

```

**Comment by ohadlevy** [comment]
@himdel one disadvantage to the ui-classic repo is that we have multiple eslint configuration that hound does not support. I wonder if we can unify the rules going forward or that reason enough warrants us from using it in the first place.

**Comment by himdel** [comment]
> you could see an example of hound output at ohadlevy/manageiq-ui-classic#5

Aah, so.. it just sends one mail, but still comments on every single error separately?

That's still a **big** :-1: from me.


> we have multiple eslint configuration that hound does not support

That's IMO a blocker. We have separate eslint config for specs, for angular1 code, for es5 code and for es6 code.

It is theoretically possible to have just one ruleset js file because eslint actually reevaluates the config for each file and the path can be glimpsed from eslint internal structures, that's how our eslint config originally started .. but it was very hacky and just having this as separate rulesets turned out to be much saner, so I'd be reluctant to go back there.
