### ISSUE TITLE
[RFE] Please add a "assign_reviewer" alias for "add_reviewer"

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/miq_bot#453]
I continue to accidentally try to accidentally use the command "assign_reviewer" (instead of "add_reviewer") because that's the terminology that github currently uses.

Can we please add an alias so that either works?

**Comment by bdunne** [comment]
From what I've seen Github uses the term "Request a review".  "Assigning" a PR is different and has a different meaning, so I'd prefer not to add a command "assign_reviewer" because it's less clear to me whether this will affect assignees or reviewers.
Would "request_review" or something similar to that help?

**Comment by djberg96** [comment]
@bdunne Ok, I can see your point. Let's go with request_review. :)

**Comment by djberg96** [comment]
@bdunne Did this happen?

**Comment by Fryguy** [comment]
Searching the code I don't see it, so I'd say no,

**Comment by bdunne** [comment]
No, it doesn't look like anyone has gotten to this yet.
