### ISSUE TITLE
On a PR with a BZ, add the PR link to the BZ and flip it to ON_DEV

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/miq_bot#49]

**Comment by Fryguy** [comment]
Check for NEW/ASSIGNED.

If not those states alert the creator through Bugzilla needinfo (perhaps they typoed the BZ ticket)

**Comment by carbonin** [comment]
Is there a specific comment string we would want for this when posting the PR link?  Right now I have it just sending the link.

**Comment by Fryguy** [comment]
Probably just the link is sufficient for now.   Eventually it can probably go into the external trackers

**Comment by carbonin** [comment]
ActiveBugzilla doesn't seem to expose the email address associated with a needinfo flag.  Would just adding the flag be okay (because the person we are notifying would be the creator of the bug anyway)?

Also, should there be a separate comment explaining why the needinfo flag was set?
Maybe something like "Detected commit referencing this ticket with status <status>"?
